version: "2"

networks:
  byfn:
    external:
      name: first-network
services:
  caliper_1.4:
    container_name: caliper
    image: hyperledger/caliper:0.3.2 
    command: launch master
    environment:
      - CALIPER_PROJECTCONFIG=caliper-config.yaml
      - CALIPER_BIND_SUT=fabric:1.4.8
      - CALIPER_BENCHCONFIG=benchmark-fixed-asset.yaml
      - CALIPER_NETWORKCONFIG=caliper-net-config.yaml
    volumes:
      - /home/user/thesis-good-reports/fabric-samples/raft-4node-swarm:/hyperledger/caliper/workspace
    networks:
    - byfn
