
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric

info:
  Version: 1.4.8
  Size: 2 Orgs with 2 Peer
  Orderer: Raft
  Distribution: Multi Host
  StateDB: GoLevelDB

clients:
  client0.org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/187504b530cea0a31e0e43afd4e465b4ba17065b8854d64533c2628d5e905490_sk
      clientSignedCert:
        path: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

  client0.org2.example.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/6025901e11e84d3f0599da614986b0628dcbbe051229b18016bfa15faa8ed952_sk
      clientSignedCert:
        path: crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem


channels:
  mychannel:
    created: true
    orderers: ['orderer.example.com','orderer2.example.com','orderer3.example.com','orderer4.example.com'] #,'orderer5.example.com']
    peers: 
      peer0.org1.example.com:
       eventSource: true
       endorsingPeer: true
      peer1.org1.example.com:
       eventSource: true
       endorsingPeer: true
      peer0.org2.example.com:
       eventSource: true
       endorsingPeer: true
      peer1.org2.example.com:
       eventSource: true
       endorsingPeer: true

    chaincodes:
     - id: fixed-asset
       version: v1
#       language: golang
 #      path: src/fabric/samples/fabcar/go
    #dorsement-policy: { "identities": [{ "role": { "name": "member", "mspId": "Org1MSP" }},{ "role": { "name": "member", "mspId": "Org2MSP" }}],"policy": {"2-of": [{ "signed-by": 0}, { "signed-by": 1 }]}}
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    - peer1.org1.example.com
    adminPrivateKey:
      path: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/187504b530cea0a31e0e43afd4e465b4ba17065b8854d64533c2628d5e905490_sk
    signedCert:
      path: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem


  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    - peer1.org2.example.com
    adminPrivateKey:
      path: crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/6025901e11e84d3f0599da614986b0628dcbbe051229b18016bfa15faa8ed952_sk
    signedCert:
      path: crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem


peers:
  peer0.org1.example.com:
    url: grpcs://peer0.org1.example.com:7051
    tlsCACerts:
      path:  crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem
  
  peer1.org1.example.com:
    url: grpcs://peer1.org1.example.com:7051
    tlsCACerts:
      path:  crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer0.org2.example.com:
    url: grpcs://peer0.org2.example.com:7051
    tlsCACerts:
      path:  crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

  peer1.org2.example.com:
    url: grpcs://peer1.org2.example.com:7051
    tlsCACerts:
      path:  crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

orderers:
  orderer.example.com:
    url: grpcs://orderer.example.com:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
        path: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  orderer2.example.com:
    url: grpcs://orderer2.example.com:7050
    grpcOptions:
      ssl-target-name-override: orderer2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
        path: crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  orderer3.example.com:
    url: grpcs://orderer3.example.com:7050
    grpcOptions:
      ssl-target-name-override: orderer3.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
        path: crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  orderer4.example.com:
    url: grpcs://orderer4.example.com:7050
    grpcOptions:
      ssl-target-name-override: orderer4.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
        path: crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  orderer5.example.com:
    url: grpcs://orderer5.example.com:8050
    grpcOptions:
      ssl-target-name-override: orderer5.example.com
    tlsCACerts:
        path: crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

