version: "2"

networks:
  byfn:
    external:
      name: first-network

services:
  caliper_worker_0:
    container_name: caliper_w_1
    image: hyperledger/caliper:0.3.2
    command: launch worker --caliper-flow-only-test --caliper-fabric-loadbalancing tx  --caliper-fabric-gateway-usegateway --caliper-fabric-gateway-discovery --no-caliper-fabric-gateway-gatewaylocalhost --caliper-worker-communication-method mqtt --caliper-worker-remote --caliper-worker-communication-address mqtt://mosquitto:1883
    environment:
      - CALIPER_BIND_SUT=fabric:1.4.8
      - CALIPER_BENCHCONFIG=raft-4node-swarm/benchmark-fabcar.yaml
      - CALIPER_NETWORKCONFIG=raft-4node-swarm/caliper-net-config.yaml
    volumes:
      - /home/user/caliper-benchmarks:/hyperledger/caliper/workspace
    networks:
    - byfn

  caliper_worker_1:
    container_name: caliper_w_2
    image: hyperledger/caliper:0.3.2
    command: launch worker --caliper-flow-only-test --caliper-fabric-loadbalancing tx  --caliper-fabric-gateway-usegateway --caliper-fabric-gateway-discovery --no-caliper-fabric-gateway-gatewaylocalhost --caliper-worker-communication-method mqtt --caliper-worker-remote --caliper-worker-communication-address mqtt://mosquitto:1883
    environment:
      - CALIPER_BIND_SUT=fabric:1.4.8
      - CALIPER_BENCHCONFIG=raft-4node-swarm/benchmark-fabcar.yaml
      - CALIPER_NETWORKCONFIG=raft-4node-swarm/caliper-net-config.yaml
    volumes:
      - /home/user/caliper-benchmarks:/hyperledger/caliper/workspace
    networks:
    - byfn

  caliper_worker_2:
    container_name: caliper_w_3
    image: hyperledger/caliper:0.3.2
    command: launch worker --caliper-flow-only-test --caliper-fabric-loadbalancing tx  --caliper-fabric-gateway-usegateway --caliper-fabric-gateway-discovery --no-caliper-fabric-gateway-gatewaylocalhost --caliper-worker-communication-method mqtt --caliper-worker-remote --caliper-worker-communication-address mqtt://mosquitto:1883
    environment:
      - CALIPER_BIND_SUT=fabric:1.4.8
      - CALIPER_BENCHCONFIG=raft-4node-swarm/benchmark-fabcar.yaml
      - CALIPER_NETWORKCONFIG=raft-4node-swarm/caliper-net-config.yaml
    volumes:
      - /home/user/caliper-benchmarks:/hyperledger/caliper/workspace
    networks:
    - byfn

  caliper_worker_3:
    container_name: caliper_w_4
    image: hyperledger/caliper:0.3.2
    command: launch worker --caliper-flow-only-test --caliper-fabric-loadbalancing tx  --caliper-fabric-gateway-usegateway --caliper-fabric-gateway-discovery --no-caliper-fabric-gateway-gatewaylocalhost --caliper-worker-communication-method mqtt --caliper-worker-remote --caliper-worker-communication-address mqtt://mosquitto:1883
    environment:
      - CALIPER_BIND_SUT=fabric:1.4.8
      - CALIPER_BENCHCONFIG=raft-4node-swarm/benchmark-fabcar.yaml
      - CALIPER_NETWORKCONFIG=raft-4node-swarm/caliper-net-config.yaml
    volumes:
      - /home/user/caliper-benchmarks:/hyperledger/caliper/workspace
    networks:
    - byfn


  caliper_worker_4:
    container_name: caliper_w_5
    image: hyperledger/caliper:0.3.2
    command: launch worker --caliper-flow-only-test --caliper-fabric-loadbalancing tx  --caliper-fabric-gateway-usegateway --caliper-fabric-gateway-discovery --no-caliper-fabric-gateway-gatewaylocalhost --caliper-worker-communication-method mqtt --caliper-worker-remote --caliper-worker-communication-address mqtt://mosquitto:1883
    environment:
      - CALIPER_BIND_SUT=fabric:1.4.8
      - CALIPER_BENCHCONFIG=raft-4node-swarm/benchmark-fabcar.yaml
      - CALIPER_NETWORKCONFIG=raft-4node-swarm/caliper-net-config.yaml
    volumes:
      - /home/user/caliper-benchmarks:/hyperledger/caliper/workspace
    networks:
    - byfn

  caliper_worker_5:
    container_name: caliper_w_6
    image: hyperledger/caliper:0.3.2
    command: launch worker --caliper-flow-only-test --caliper-fabric-loadbalancing tx  --caliper-fabric-gateway-usegateway --caliper-fabric-gateway-discovery --no-caliper-fabric-gateway-gatewaylocalhost --caliper-worker-communication-method mqtt --caliper-worker-remote --caliper-worker-communication-address mqtt://mosquitto:1883
    environment:
      - CALIPER_BIND_SUT=fabric:1.4.8
      - CALIPER_BENCHCONFIG=raft-4node-swarm/benchmark-fabcar.yaml
      - CALIPER_NETWORKCONFIG=raft-4node-swarm/caliper-net-config.yaml
    volumes:
      - /home/user/caliper-benchmarks:/hyperledger/caliper/workspace
    networks:
    - byfn
  caliper_worker_6:
    container_name: caliper_w_7
    image: hyperledger/caliper:0.3.2
    command: launch worker --caliper-flow-only-test --caliper-fabric-loadbalancing tx  --caliper-fabric-gateway-usegateway --caliper-fabric-gateway-discovery --no-caliper-fabric-gateway-gatewaylocalhost --caliper-worker-communication-method mqtt --caliper-worker-remote --caliper-worker-communication-address mqtt://mosquitto:1883
    environment:
      - CALIPER_BIND_SUT=fabric:1.4.8
      - CALIPER_BENCHCONFIG=raft-4node-swarm/benchmark-fabcar.yaml
      - CALIPER_NETWORKCONFIG=raft-4node-swarm/caliper-net-config.yaml
    volumes:
      - /home/user/caliper-benchmarks:/hyperledger/caliper/workspace
    networks:
    - byfn
  caliper_worker_7:
    container_name: caliper_w_8
    image: hyperledger/caliper:0.3.2
    command: launch worker --caliper-flow-only-test --caliper-fabric-loadbalancing tx  --caliper-fabric-gateway-usegateway --caliper-fabric-gateway-discovery --no-caliper-fabric-gateway-gatewaylocalhost --caliper-worker-communication-method mqtt --caliper-worker-remote --caliper-worker-communication-address mqtt://mosquitto:1883
    environment:
      - CALIPER_BIND_SUT=fabric:1.4.8
      - CALIPER_BENCHCONFIG=raft-4node-swarm/benchmark-fabcar.yaml
      - CALIPER_NETWORKCONFIG=raft-4node-swarm/caliper-net-config.yaml
    volumes:
      - /home/user/caliper-benchmarks:/hyperledger/caliper/workspace
    networks:
    - byfn
  caliper_worker_8:
    container_name: caliper_w_9
    image: hyperledger/caliper:0.3.2
    command: launch worker --caliper-flow-only-test --caliper-fabric-loadbalancing tx  --caliper-fabric-gateway-usegateway --caliper-fabric-gateway-discovery --no-caliper-fabric-gateway-gatewaylocalhost --caliper-worker-communication-method mqtt --caliper-worker-remote --caliper-worker-communication-address mqtt://mosquitto:1883
    environment:
      - CALIPER_BIND_SUT=fabric:1.4.8
      - CALIPER_BENCHCONFIG=raft-4node-swarm/benchmark-fabcar.yaml
      - CALIPER_NETWORKCONFIG=raft-4node-swarm/caliper-net-config.yaml
    volumes:
      - /home/user/caliper-benchmarks:/hyperledger/caliper/workspace
    networks:
    - byfn

  caliper_worker_9:
    container_name: caliper_w_10
    image: hyperledger/caliper:0.3.2
    command: launch worker --caliper-flow-only-test --caliper-fabric-loadbalancing tx  --caliper-fabric-gateway-usegateway --caliper-fabric-gateway-discovery --no-caliper-fabric-gateway-gatewaylocalhost --caliper-worker-communication-method mqtt --caliper-worker-remote --caliper-worker-communication-address mqtt://mosquitto:1883
    environment:
      - CALIPER_BIND_SUT=fabric:1.4.8
      - CALIPER_BENCHCONFIG=raft-4node-swarm/benchmark-fabcar.yaml
      - CALIPER_NETWORKCONFIG=raft-4node-swarm/caliper-net-config.yaml
    volumes:
      - /home/user/caliper-benchmarks:/hyperledger/caliper/workspace
    networks:
    - byfn

